#!/usr/bin/env python3
"""Generate .claude/.scout-cache/registry-digest.md from the registry files.

The digest exists so an expensive agent can see every registry entry without
reading roughly 229,000 tokens of registry text. Two rules govern it, and the
first is the reason the mechanism exists at all:

  1. The index is COMPLETE. Every entry in every registry appears, always.
     A digest that omits a title hides exactly the entry the Data-First
     protocol exists to surface, and the architect then writes a parallel
     implementation of something that already existed.

  2. Only bodies are elided. A reader who wants one takes the file and line
     reference and reads that entry alone.

Run after editing any registry:

    py -3 .claude/scripts/generate_registry_digest.py

Exits non-zero if any emitted reference does not resolve, so a stale digest
fails loudly rather than misdirecting a reader.
"""
from __future__ import annotations

import os
import re
import sys

REG = '.claude/registries'
OUT = '.claude/.scout-cache/registry-digest.md'
DOMAINS = ['backend', 'frontend', 'data', 'trading', 'general']

BULLET = re.compile(r'^- \*\*(.+?)\*\*')          # MECHANISMS / VOCABULARY
DATED = re.compile(r'^#{2,3} (\d{4}-\d{2}-\d{2} .+)$')  # JOURNAL
HEADING = re.compile(r'^(#{2,3}) (.+)$')          # INTEGRATION


def read(path):
    if not os.path.exists(path):
        return []
    with open(path, encoding='utf-8') as fh:
        return fh.read().splitlines()


def entries(path, pattern, group=1):
    """Return (title, line_number) for every match, line numbers 1-based."""
    out = []
    for i, ln in enumerate(read(path), 1):
        m = pattern.match(ln)
        if m:
            out.append((m.group(group).strip(), i))
    return out


def tier_split(path, pattern):
    """Split a two-tier registry into (universal, project) entry lists."""
    uni, proj, tier = [], [], None
    for i, ln in enumerate(read(path), 1):
        if ln.startswith('## Universal'):
            tier = 'U'
            continue
        if ln.startswith('## Project:'):
            tier = 'P'
            continue
        m = pattern.match(ln)
        if m:
            (uni if tier == 'U' else proj).append((m.group(1).strip(), i))
    return uni, proj


def clean(title, limit=96):
    t = re.sub(r'\s+', ' ', title).strip()
    return t if len(t) <= limit else t[:limit - 1] + '…'


def emit_group(out, label, path, items, refs):
    if not items:
        return
    rel = path[len('.claude/'):]
    out.append(f'### {label} — `{rel}` ({len(items)} entries)')
    out.append('')
    for title, line in items:
        out.append(f'- {clean(title)} [{rel}:{line}]')
        refs.append((path, line, title))
    out.append('')


def main():
    out, refs = [], []
    out += [
        '# Registry Digest',
        '',
        'Complete index of every registry entry, with a file and line reference for each.',
        'Read an entry by opening its reference; do not read a whole registry.',
        '',
        '**Generated by** `.claude/scripts/generate_registry_digest.py`. Re-run it after editing',
        'any registry, or this file goes stale silently.',
        '',
        '**The index is never trimmed.** Every entry appears. Only bodies are elided — a digest',
        'that omitted a title would hide the very entry an architect needed to extend.',
        '',
        '---',
        '',
    ]

    # ---- MECHANISMS -------------------------------------------------------
    out += ['## Mechanisms', '']
    uni, proj = tier_split(f'{REG}/MECHANISMS.md', BULLET)
    emit_group(out, 'Universal', f'{REG}/MECHANISMS.md', uni, refs)
    if proj:
        emit_group(out, 'Project (top level)', f'{REG}/MECHANISMS.md', proj, refs)
    for d in DOMAINS:
        p = f'{REG}/MECHANISMS/{d}.md'
        emit_group(out, d.capitalize(), p, entries(p, BULLET), refs)

    # ---- VOCABULARY -------------------------------------------------------
    out += ['---', '', '## Vocabulary', '']
    uni, proj = tier_split(f'{REG}/VOCABULARY.md', BULLET)
    emit_group(out, 'Universal', f'{REG}/VOCABULARY.md', uni, refs)
    if proj:
        emit_group(out, 'Project (top level)', f'{REG}/VOCABULARY.md', proj, refs)
    for d in DOMAINS:
        p = f'{REG}/VOCABULARY/{d}.md'
        emit_group(out, d.capitalize(), p, entries(p, BULLET), refs)

    # ---- JOURNAL ----------------------------------------------------------
    out += ['---', '', '## Journal (lessons)', '']
    p = f'{REG}/JOURNAL.md'
    j = entries(p, DATED) or entries(p, BULLET)
    emit_group(out, 'Universal', p, j, refs)
    for d in DOMAINS:
        p = f'{REG}/JOURNAL/{d}.md'
        emit_group(out, d.capitalize(), p, entries(p, DATED), refs)

    # ---- INTEGRATION ------------------------------------------------------
    out += ['---', '', '## Integration surfaces', '']
    p = f'{REG}/INTEGRATION.md'
    heads = []
    for i, ln in enumerate(read(p), 1):
        m = HEADING.match(ln)
        if m:
            prefix = '' if len(m.group(1)) == 2 else '  '
            heads.append((prefix + m.group(2), i))
    emit_group(out, 'Sections', p, heads, refs)

    body = '\n'.join(out).rstrip() + '\n'
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(body)

    # ---- verification -----------------------------------------------------
    bad = []
    for path, line, title in refs:
        lines = read(path)
        if line < 1 or line > len(lines):
            bad.append((path, line, title, '<out of range>'))
            continue
        key = re.sub(r'[^a-z0-9]', '', title.lower())[:12]
        target = re.sub(r'[^a-z0-9]', '', lines[line - 1].lower())
        if key and key not in target:
            bad.append((path, line, title, lines[line - 1][:60]))

    approx_tokens = len(body) // 4
    print(f'wrote {OUT}')
    print(f'  entries indexed : {len(refs)}')
    print(f'  characters      : {len(body)}  (~{approx_tokens} tokens)')
    print(f'  bad references  : {len(bad)}')
    for p, l, t, a in bad[:10]:
        print(f'    {p}:{l} expected "{t[:40]}" got "{a}"')
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
